project_name: http-ping
gomod:
  proxy: true
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - freebsd
      - darwin
    goarch:
      - 386
      - amd64
      - arm64
    hooks:
      post:
        - sh -c 'upx "{{ .Path }}" || true' # run in

archives:
  -
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^README:'
      - '^gitignore:'
      - '^goreleaser:'
      - '^workflows:'
dockers:
  - image_templates:
      - "docker.io/feverch/http-ping:{{ .Tag }}"
      - "docker.io/feverch/http-ping:v{{ .Major }}"
      - "docker.io/feverch/http-ping:v{{ .Major }}.{{ .Minor }}"
      - "docker.io/feverch/http-ping:latest"
      - "ghcr.io/fever-ch/http-ping:{{ .Tag }}"
      - "ghcr.io/fever-ch/http-ping:v{{ .Major }}"
      - "ghcr.io/fever-ch/http-ping:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/fever-ch/http-ping:latest"
    dockerfile: Dockerfile.goreleaser