project_name: http-ping
gomod:
  proxy: true
before:
  hooks:
    - go mod tidy
    - go generate ./...

source:
  enabled: true

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - freebsd
      - darwin
    goarch:
      - 386
      - amd64
      - arm64

archives:
  -
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^README:'
      - '^gitignore:'
      - '^goreleaser:'
      - '^workflows:'
dockers:
  - image_templates:
      - "docker.io/feverch/http-ping:{{ .Tag }}"
      - "docker.io/feverch/http-ping:v{{ .Major }}"
      - "docker.io/feverch/http-ping:v{{ .Major }}.{{ .Minor }}"
      - "docker.io/feverch/http-ping:latest"
      - "ghcr.io/fever-ch/http-ping:{{ .Tag }}"
      - "ghcr.io/fever-ch/http-ping:v{{ .Major }}"
      - "ghcr.io/fever-ch/http-ping:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/fever-ch/http-ping:latest"
    dockerfile: Dockerfile.goreleaser
nfpms:
  -
    homepage: https://github.com/fever-ch/http-ping
    description: Http-Ping is similar to the usual ping networking utility but instead of working on top of ICMP, it works on top of HTTP/S.
    maintainer: Raphaël P. Barazzutti
    license: Apache 2.0
    vendor: fever.ch
    bindir: /usr/bin
    suggests:
      - ca-certificates
    formats:
      - apk
      - deb
      - rpm
brews:
  -
    tap:
      owner: fever-ch
      name: homebrew-tap
    homepage: 'Http-Ping is similar to the usual ping networking utility but instead of working on top of ICMP, it works on top of HTTP/S.'
    description: 'Http-Ping is similar to the usual ping networking utility but instead of working on top of ICMP, it works on top of HTTP/S.'

