name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build, Test, Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Lint
        uses: golangci/golangci-lint-action@v2


      - name: Test & Coverage
        run: go test -v -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)