name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build, Test, Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Lint
        uses: golangci/golangci-lint-action@v2


      - name: Test & Coverage
        run: go test -v -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)